baseURL = "http://example.org/"
languageCode = "en-us"
title = "Thomas Bundle Docs"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"

  [[module.imports]]
    path = "github.com/google/docsy"
 
  
[params.ui]
  sidebar_menu_compact = true
  ul_show = 1
  sidebar_menu_foldable = true

[[menu.main]]
  name = "Docs"
  weight = 20
  url = "/docs/"

[params]
  offlineSearch = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

